
import "./globals.css";
import Layout from "@/components/layout/Layout";
import { marhey, vazirmatn } from "@/utils/fonts";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Amir khani",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${marhey.variable} ${vazirmatn.variable}  antialiased dark:bg-primary`}
      >
        <Layout>
          <div>
            <Toaster />
          </div>

          {children}
        </Layout>
      </body>
    </html>
  );
}
